WEBHOOK_PASSPHRASE = "password"
LIVE_URL = "https://api.bybit.com"
API_KEY = "cSBL3DAXa2S2Hhv5MO"
API_SECURET = "QaTm9Y9DAz5aCGe3T4chjCBvV9zpN73GMbyv"
API_PASSWORD = "Janaka123!"
# ///bybit-testnet-golden
DEMO_URL = "https://api-testnet.bybit.com"
DEMO_API_KEY = "8UOptNa4ym012V67Zj"
DEMO_API_SECURET = "qdB1mvfLjP5KnMNuHZmfq0HKr5WEHM3KdQKv"
DEMO_API_PASSWORD = "Janaka123!"