WEBHOOK_PASSPHRASE = "password"
LIVE_URL = "https://api.bybit.com"
API_KEY = "cSBL3DAXa2S2Hhv5MO"
API_SECURET = "QaTm9Y9DAz5aCGe3T4chjCBvV9zpN73GMbyv"
API_PASSWORD = "greentrees1111"
# ///bybit-testnet-golden
DEMO_URL = "https://api-testnet.bybit.com"
DEMO_API_KEY = "qneQGZVH9uJvg5dmal"
DEMO_API_SECURET = "4xHX57pEKSUWLt1ET4dqxIu81DGmjBWTgEGD"
DEMO_API_PASSWORD = "greentrees1111"